cal/urls.py
# cal/urls.py

from django.urls import path, include, re_path
from . import views

app_name = 'cal'
urlpatterns = [
    re_path(r'', views.agenda, name='agenda'),
]

permagora/urls.py
from django.urls import path, include, re_path
from permagora import views
from django.views.generic import TemplateView
#from fcm_django.api.rest_framework import FCMDeviceAuthorizedViewSet

# On import les vues de Django, avec un nom spécifique
from django.contrib.auth.decorators import login_required

# admin.autodiscover()
from django.contrib import admin

app_name = 'permagora'

urlpatterns = [
    path('gestion/', admin.site.urls),
    re_path(r'^summernote/', include('local_summernote.urls')),
    re_path(r'^captcha/', include('local_captcha.urls')),
    re_path(r'^$', views.bienvenue, name='bienvenue'),
    re_path(r'^planSite/$', views.planSite, name='planSite'),
    re_path(r'^risques/$', views.risques, name='risques'),
    re_path(r'^introduction/$', views.introduction, name='introduction'),
    re_path(r'^preambule/$', views.preambule, name='preambule'),
    re_path(r'^preconisations/$', views.preconisations, name='preconisations'),
    re_path(r'^faq/$', views.faq, name='faq'),
    re_path(r'^contact/$', views.contact, name='contact', ),
    re_path(r'^signer/$', views.signer, name='signer', ),
    re_path(r'^designer/$', views.designer, name='designer', ),
    re_path(r'^statistiques/$', views.statistiques, name='statistiques', ),
    re_path(r'^signataires/$', views.signataires, name='signataires', ),

    re_path(r'^accounts/profil/(?P<user_id>[0-9]+)/$', login_required(views.profil), name='profil', ),
    re_path(r'^accounts/profil/(?P<user_username>[-\w.]+)/$', login_required(views.profil_nom), name='profil_nom', ),
    re_path(r'^accounts/profile/$', login_required(views.profil_courant), name='profil_courant', ),

    re_path(r'^merci/$', views.merci, name='merci'),
    path('auth/', include('django.contrib.auth.urls')),
    re_path(r'^propositions/$', views.propositions, name='propositions', ),
    re_path(r'^organisationPermagora/$', views.organisationPermagora, name='organisationPermagora', ),
    re_path(r'^presentationPermagora/$', views.presentationPermagora, name='presentationPermagora', ),
    re_path(r'^cgu/$', views.cgu, name='cgu', ),
    re_path(r'^liens/$', views.liens, name='liens', ),
    re_path(r'^fairedon/$', views.fairedon, name='fairedon', ),
    re_path(r'^contact_admins/$', views.contact_admins, name='contact_admins',),

    re_path(r'^ajouterPoleCharte/$', views.ajouterPoleCharte, name='ajouterPoleCharte', ),
    re_path(r'^voirProposition/(?P<slug>[-\w]+)$', views.voirProposition, name='voirProposition', ),
    re_path(r'^ajouterVote_plus/(?P<slug>[-\w]+)$', views.ajouterVote_plus, name='ajouterVote_plus', ),
    re_path(r'^ajouterVote_moins/(?P<slug>[-\w]+)$', views.ajouterVote_moins, name='ajouterVote_moins', ),
    path(r'ajouterProposition/', views.ajouterProposition, name='ajouterProposition'),
    path(r'voirNotifications/', views.voirNotifications, name='voirNotifications'),

    re_path(r'^modifierProposition/(?P<slug>[-\w]+)$',
        login_required(views.ModifierProposition.as_view(), login_url='/auth/login/'), name='modifierProposition'),
    ]
urlpatterns += [
    re_path(r'^robots\.txt$', TemplateView.as_view(template_name="permagora/robots.txt", content_type='text/plain')),
]

from django.conf import settings
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'permagora.views.handler404'
handler500 = 'permagora.views.handler500'
handler400 = 'permagora.views.handler400'
handler403 = 'permagora.views.handler403'

vote/urls.py
# -*- coding: utf-8 -*-
"""bourseLibre URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  re_path(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  re_path(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from vote__ import urls as vote_urls
    2. Add a URL to urlpatterns:  re_path(r'^vote__/', include(vote_urls))
"""
from django.urls import path, include, re_path
from . import views#, views_wizard
from django.contrib.auth.decorators import login_required


app_name = 'vote'

urlpatterns = [
    re_path(r'^$', views.accueil, name="accueil"),
    path(r'suffrages/', login_required(views.ListeSuffrages.as_view(), login_url='/auth/login/'), name="index"),
    re_path(r'^suffrage/(?P<slug>[-\w]+)$', views.lireSuffrage, name='lireSuffrage'),
    re_path(r'^modifierSuffrage/(?P<slug>[-\w]+)$', login_required(views.ModifierSuffrage.as_view(), login_url='/auth/login/'), name='modifierSuffrage'),
    re_path(r'^supprimerSuffrage/(?P<slug>[-\w]+)$',
        login_required(views.SupprimerSuffrage.as_view(), login_url='/auth/login/'), name='supprimerSuffrage'),

    path(r'ajouterSuffrage/<str:article_slug>', login_required(views.ajouterSuffrage), name='ajouterSuffrage'),
    re_path(r'^voter/(?P<slug>[-\w]+)$', login_required(views.voter), name='voter'),
    re_path(r'^modifierVote/(?P<slug>[-\w]+)$', login_required(views.ModifierVote.as_view(), login_url='/auth/login/'), name='modifierVote'),
    re_path(r'^suffrage/resultat/(?P<slug>[-\w]+)$', views.resultatsSuffrage, name='resultatsSuffrage'),
    re_path(r'^modifierCommentaireSuffrage/(?P<id>[0-9]+)$',
        login_required(views.ModifierCommentaireSuffrage.as_view(), login_url='/auth/login/'),
        name='modifierCommentaireSuffrage'),
    re_path(r'^suivre_suffrages/$', views.suivre_suffrages, name='suivre_suffrages'),
    re_path(r'^suffrage/(?P<slug>[-\w]+)/ajouterQuestion$', views.ajouterQuestion, name='ajouterQuestion'),
    re_path(r'^suffrage/(?P<slug>[-\w]+)/ajouterQuestionB$', views.ajouterQuestionB, name='ajouterQuestionB'),
    re_path(r'^suffrage/(?P<slug>[-\w]+)/ajouterQuestionM$', views.ajouterQuestionM, name='ajouterQuestionM'),

    path(r'supprimerQuestionB/<str:slug>/<int:id_question>', views.supprimerQuestionB, name='supprimerQuestionB'),
    path(r'supprimerQuestionM/<str:slug>/<int:id_question>', views.supprimerQuestionM, name='supprimerQuestionM'),
    path(r'supprimerPropositionM/<str:slug><int:id_question>/<int:id_proposition>', views.supprimerPropositionM, name='supprimerPropositionM'),
    #re_path(r'ajouter_suffrage/$', views_wizard.SuffrageWizard.as_view()),

    path(r'ajouterSuffrage_article/<str:article_slug>', views.ajouterSuffrage_article, name='ajouterSuffrage_article'),
    path(r'ajouterSondageBinaire/<str:article_slug>', views.ajouterSondageBinaire, name='ajouterSondageBinaire'),
    path(r'ajouterVoteBinaire/<int:sondageBinaire_pk>/<str:reponse_b>/', login_required(views.ajouterVoteBinaire), name='ajouterVoteBinaire'),
    path(r'modifierSondageB/<int:pk>', login_required(views.ModifierSondageB.as_view()), name='modifierSondageB'),
    path(r'supprimerSondageB/<int:pk>', login_required(views.SupprimerSondageB.as_view()), name='supprimerSondageB'),
    path(r'get_resultatSondageB/<int:sondage_pk>', views.get_resultatSondageB, name='get_resultatSondageB'),
]

vote/models.py
import itertools

from django.db import models
from bourseLibre.models import Profil, Asso
from django.urls import reverse
from django.utils import timezone
from actstream.models import followers
from bourseLibre.models import Suivis
from actstream import action
from functools import cmp_to_key
from django.core.validators import MinLengthValidator
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

class Choix():
    type_vote_bm =(('', '-----------'), (0, "Question binaire"))

    vote_ouinon = (('', '-----------'),
                     (0, ("Oui")),
                    (1, ("Non")),
                    (2, ("Ne se prononce pas")))

    type_vote = (('', '-----------'),
                     ('0', ("Vote d'un projet")),
                    ('1', ("Vote d'une décision")),
                    ('2', ("Sondage")),
                    ('3', ("Election")))

    vote_majoritaire = {'0':(('', '------------ Exprimez votre opinion --------------'),
                            (0, ("pas du tout d'accord")),
                            (1, ("Plutot pas d'accord")),
                            (2, ("Neutre")),
                            (3, ("Plutot d'accord")),
                            (4, ("Tout à fait d'accord"))),
                    '1':(('', '---------- Choisissez une note ---------------'),
                            (0, ("0 (le plus bas score)")),
                            (1, ("1")),
                            (2, ("2")),
                            (3, ("3")),
                            (4, ("4 (le plus haut score)"))),
                    '2': (('', '------------------ Choisissez une appréciation ---------------'),
                         (0, ("Pas du tout satisfaisant")),
                         (1, ("Pas très satisfaisant")),
                         (2, ("Neutre ")),
                         (3, ("Assez satisfaisant")),
                         (4, ("Tout-à-fait satisfaisant"))),
    }

    type_echelledevote = (('', '-----------'),
                    ('0', ("Opinion: de 'pas du tout d'accord' à 'tout à fait d'accord")),
                     ('1', ("Note : de 0 à 4")),
                     ('2', ("Appréciation : de 'pas du tout satisfaisant' à 'tout à fait satisfaisant'")),
                          )

    couleurs_annonces = {
            '0':"#d1ecdc",
            'Coordination':"#D4CF7D",
            '1':"#E0E3AB",
            'Potager':"#AFE4C1",
            'PPAM':"#fff2a0",
            'Arbres':"#B2AFE4",
            'Administratif':"#d0f4de",
            '2':"#caf9b7",
            'Permaculture':"#ced2d3",
            'Documentation':"#349D9B",
            'Point':"#bccacf",
            'Autre':"#87bfae",
            'Ecovillage':"#cebacf",
            'Jardin':"#fffdcc",
            'Altermarché':"#daffb3",
            'aa':'#ddd0a8',

        }

    def get_couleur(categorie):
        try:
            return Choix.couleurs_annonces[categorie]
        except:
            return Choix.couleurs_annonces["Autre"]

def getStrFromChoix_majoritaire(type_choix, choix):
    return Choix.vote_majoritaire[type_choix][[y[0] for y in Choix.vote_majoritaire[type_choix]].index(choix)][1]
def getStrFromChoix_ouinon(choix):
    return Choix.vote_ouinon[[y[0] for y in Choix.vote_ouinon].index(choix)][1]

def sort_candidats(a, b):
    """
    Sort candidates by their majority gauge.

    a & b are the majority gauges of the candidates A & B
    (p_A, α_A, q_A) & (p_B, α_B, q_B)
    where
    - α is the majority grade;
    - p the percentage of votes strictly above α;
    - q the percentage of votes strictly below α.
    thus, A > B ⇔ α_A > α_B || (α_A == α_B && (p_A > max(q_A, p_B, q_B) || q_B > max(p_A, q_A, p_B)))
    (eq. 2, p.11 of the second article in README.md)
    """
    a, b = [float(x) for x in a.majority_gauge()], [float(x) for x in b.majority_gauge()]

    if a[1] > b[1]:
        return 1
    if b[1] > a[1]:
        return -1
    if a[0] > max(a[2], b[0], b[2]):
        return 1
    if b[0] > max(b[2], a[0], a[2]):
        return -1
    if b[2] > max(a[0], a[2], b[0]):
        return 1
    if a[2] > max(b[0], b[2], a[0]):
        return -1
    return 0


class SuffrageBase(models.Model):
    type_vote = models.CharField(max_length=30,
        choices=(Choix.type_vote), default='', verbose_name=_("Type de vote"))
    titre = models.CharField(max_length=100, verbose_name=_("Titre du sondage"))
    auteur = models.ForeignKey(Profil, on_delete=models.CASCADE, related_name='auteur_suffrage')
    slug = models.SlugField(max_length=100)
    description = models.TextField(null=True, verbose_name=_("Description du contexte"))
    date_creation = models.DateTimeField(verbose_name=_("Date de parution"), default=timezone.now)
    date_dernierMessage = models.DateTimeField(verbose_name=_("Date du dernier message"), auto_now=False, blank=True, null=True)
    date_modification = models.DateTimeField(verbose_name=_("Date de modification"), default=timezone.now)
    estArchive = models.BooleanField(default=False, verbose_name=_("Archiver la proposition"))
    estAnonyme = models.BooleanField(default=False, verbose_name=_("Vote anonyme"))

    start_time = models.DateField(verbose_name=_("Date de début du vote"), null=True,blank=False, help_text="jj/mm/année")
    end_time = models.DateField(verbose_name=_("Date de fin du vote (inclu)"),  null=True,blank=False, help_text="jj/mm/année")
    asso = models.ForeignKey(Asso, on_delete=models.SET_NULL, null=True)
    article = models.ForeignKey("blog.Article", on_delete=models.CASCADE,
                                help_text="Article associé",
                                blank=True, null=True)

    class Meta:
        abstract = True

    @property
    def get_logo_nomgroupe_html(self, taille=18):
        if self.article:
            return self.article.get_logo_nomgroupe_html
        return self.asso.get_logo_nomgroupe_html


class Suffrage(SuffrageBase):
    class Meta:
        ordering = ('-date_creation', )
        db_table = 'suffrage'

    def __str__(self):
        return self.titre

    def get_absolute_url(self):
        return reverse('vote:lireSuffrage', kwargs={'slug':self.slug})

    def get_modifQuestions_url(self):
        return reverse('vote:ajouterQuestion', kwargs={'slug':self.slug})

    def save(self, userProfile=None, *args, **kwargs):
        ''' On save, update timestamps '''
        emails = []
        if not self.id:
            self.date_creation = timezone.now()
            suivi, created = Suivis.objects.get_or_create(nom_suivi='suffrages')
            titre = "Nouveau vote"
            message = userProfile.username + " a lancé un nouveau vote ["+ str(self.asso.nom) +"]: '<a href='https://www.perma.cat"+ self.get_absolute_url() + "'>"+ self.titre + "</a>'"
            emails = [suiv.email for suiv in followers(suivi) if userProfile != suiv and self.est_autorise(suiv)]

        retour = super(Suffrage, self).save(*args, **kwargs)

        if emails:
            action.send(self, verb='emails', url=self.get_absolute_url(), titre=titre, message=message, emails=emails)
        return retour

    def get_resultats(self):
        statut = self.get_statut
        #if statut[0] != 1:
        #    return statut[1]

        qsb, qsm = self.questions
        res_qb, res_qm = {}, {}
        for qb in qsb:
            res_qb[qb] = qb.get_resultats()
        for qm in qsm:
            res_qm[qm] = qm.get_resultats()
        return res_qb, res_qm

    @property
    def resultats(self):
        return self.get_resultats()

    @property
    def get_statut(self):
        if self.start_time <= timezone.now().date():
            if self.end_time > timezone.now().date():
                statut = ("0", "Le vote est en cours ")
            else:
                statut = ("1", "Le vote est terminé ")
        else:
            statut = ("2", "Le vote n'a pas encore démarré ")
        return statut


    @property
    def get_couleur(self):
        return Choix.get_couleur(self.type_vote)

    def est_autorise(self, user):
        return self.asso.est_autorise(user)

    @property
    def questionsB(self):
        return self.question_binaire_set.all()

    @property
    def questionsM(self):
        return self.question_majoritaire_set.all()

    @property
    def questions(self):
        return self.questionsB, self.questionsM

    @property
    def nbQuestionsB(self):
        return len(self.questionsB)

    @property
    def nbQuestionsM(self):
        return len(self.questionsM)

    @property
    def get_questionsB_html(self):
        questions_b, questions_m = self.questions

        txt = "<table class='comicGreen'> <tbody> "
        for i, q in enumerate(questions_b):
            txt += "<tr> <td>"
            txt += str(i + 1) +") "+ str(q) + "</td> "
            txt += '<td> <a class="btn btn-sm btn-danger textleft" href="' + q.get_delete_url() +'"><i class="fa fa-times"></i></a></td></tr>'
        txt += "</tbody> </table>"
        return txt

    @property
    def get_questionsM_html(self):
        questions_b, questions_m = self.questions

        txt = "<table class='comicGreen'> <tbody> <thead><tr><th>Question posée</th><th>Proposition</th></thead>"
        for i, q in enumerate(questions_m):
            txt += "<tr> <td>"
            txt += str(i+1) + ") " + str(q) + '(' + q.type_choix +')' '<a class="btn btn-sm btn-danger textleft" href="' + q.get_delete_url() +'"><i class="fa fa-times"></i></a></td> <td></td> </tr>'
            for j, p in enumerate(q.propositions):
                txt += "<tr> <td></td> <td>"
                txt += str(j + 1) + ") " + str(p) + '<a class="btn btn-sm btn-danger textleft" href="' + p.get_delete_url() +'"><i class="fa fa-times"></i></a></td> </tr>'

        txt += "</tbody> </table>"
        return txt

    @property
    def propositions(self):
        return Proposition_m.objects.filter(question_m__suffrage=self)


class Question_base(models.Model):

vote/templates/vote/accueil.html
{% extends 'vote/baseVote.html' %}
{% block subtitle %}

<div class="row">
    <div class="col textcenter">
       <h3> Bienvenue sur l'espace des élections / votes / sondages / suffrages (au choix)</h3>
    </div>
</div>

{% endblock %}
{% block content %}

<div class="row">
    <div class="col-sm-12 textcenter">
        <div class="btn-group btn-group-justified">
         <a href="{% url 'vote:index' %}">
        <button type="button" class="btn btn-success" >
               Suffrages
            </button>
            </a>
    </div>
   </div>

{% endblock %}

vote/templates/vote/ajouterSondageBinaire.html
{% extends 'vote/baseVote.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="row">
	<div class="col col-md-12 textcenter"><h3>Ajouter un Sondage </h3>
    </div>
</div>
	<hr>
{% if error_message %}
<p>
	<strong>{{ error_message }}</strong>
</p>
{% endif %}

<div class="row justify-content-sm-center">
<div class="col-sm-12 col-md-10 col-lg-9 text-center">
	<form id="myForm" class="form-horizontal" role="form" action="" method="post"
	enctype="multipart/form-data">
	{% csrf_token %}
        <input type="hidden" name="Suffrage"
		value="{{ suffrage }}"> {% include 'form_template2.html' %}
  <button type="submit" class="btn btn-primary">Valider</button>

</form>
</div>
</div>

{% endblock %}

vote/templates/vote/ajouterSuffrage.html
{% extends 'vote/baseVote.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="row">
	<div class="col col-md-12 textcenter"><h3>Ajouter un suffrage</h3>
    <h4>Etape 1 : Donnez ici les renseignements généraux du vote</h4>
    </div>
</div>
<hr>

{% include 'form_template.html' %}

{% endblock %}

vote/templates/vote/dejaVote.html
{% extends 'vote/baseVote.html' %}

{% block content %}
<h5 class="textcenter">Vous avez déjà voté</h5>
{% endblock %}

vote/templates/vote/lireSuffrage.html
{% extends 'vote/baseVote.html' %}
{% load activity_tags %}
{% load blog_filters %}
{% load vote_filters %}
{% load fontawesome_5 %}

{% block subtitle %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-8">
            <p class="infos  textepetit">Dans: <a href="{% url 'vote:index' %}?type_vote={{suffrage.type_vote}}&asso={{suffrage.asso}}"
                                                  style="background-color:{{suffrage.get_couleur}}"
                                                  class="smallcaps_h2">Suffrages/{{ suffrage.get_type_vote_display}}</a>
                , rédigé par <a href="{% url 'profil' suffrage.auteur.id %}"> {{ suffrage.auteur.username }}</a>,
                le {{ suffrage.date_creation|date:"DATE_FORMAT" }};
            </p>
        </div>
        <div class="col-md-2">
            {%if suffrage.auteur == request.user %}
            <div class="btn-group">
                <a href="{% url 'vote:modifierSuffrage' slug=suffrage.slug %}">
                    <button type="button" class="btn btn-sm btn-warning" {% if suffrage.get_statut.0 != '2' %} disabled{% endif %}>
                        <span class="glyphicon glyphicon-plus"></span>&nbsp;Modifier
                    </button>
                </a>
                <a href="{% url 'vote:supprimerSuffrage' slug=suffrage.slug %}">
                    <button type="button" class="btn btn-sm btn-danger" {% if suffrage.get_statut.0 != '2' %} disabled{% endif %}>
                        <span class="glyphicon glyphicon-plus"></span>&nbsp;Supprimer
                    </button>
                </a>
                {%if request.user.is_superuser %}
                <a href="https://www.perma.cat/gestion/vote/suffrage/{{article.id}}/change/">
                    <button type="button" class="btn btn-sm btn-danger">
                        <span class="glyphicon glyphicon-plus">&nbsp;Admin</span>
                    </button>
                </a>
                {% endif %}
            </div>
            {%endif%}
        </div>
    </div>

</div>

{% endblock %}
{% block content %}
<div class="contenu suffrage article">
    <div class="row titre_fiche titre-article-forum">
        <div class="col textcenter">
            <h3>
                {% if suffrage.estArchive%}
                <span class="badge badge-light" title="Article archivé">archivé </span>
                {%endif%}
                {% if suffrage.estModifiable%}
                <span class="fa fa-edit" title="Article modifiable">    </span>
                {%endif%}
                {{ suffrage.titre }}
            </h3>
        </div>
    </div>

<div class="row">
    <div class="col-sm-12 textcenter">
        <p>
            {{suffrage.get_logo_nomgroupe_html|safe }}
        <p>
            {%if suffrage.start_time%}
            <a href="{% url 'cal:agenda' %} " class="textepetit">
                Du {{ suffrage.start_time|date:"d/m/Y" }} au {{ suffrage.end_time|date:"d/m/Y" }}
            </a>
            {% endif %}
        </p>
        <p>Article lié : <a href="{{ suffrage.article.get_absolute_url }}">{{ suffrage.article }}</a></p>
        {%if request.user.is_superuser %}
        {% endif %}
        <p>
            {%if suffrage.get_statut.0 == "1" %}<a href="{% url 'vote:resultatsSuffrage' slug=suffrage.slug %}"> {% endif %}
            <button {% if suffrage.get_statut.0 == '1' %} {% else %} disabled {% endif %}
                    class="btn {%if suffrage.get_statut.0 == 0 %}btn-success {% else %} btn-warning{% endif %}">
                {{suffrage.get_statut.1}} {%if suffrage.get_statut.0 == "1"%}-> Voir les résultats{% endif %}
            </button>
            {%if suffrage.get_statut.0 == 1%}</a>{% endif %}
        </p>

        <div class="row justify-content-center">
            <div class="col-sm-12 textcenter">
                {% if suffrage.get_statut.0 == "0" %}
                {%if not vote %}
                <p><a href="{% url 'vote:voter' slug=suffrage.slug %}" class="btn btn-success">Voter</a></p>
                {% else %}
                <div class="textcenter"><a href="{% url 'vote:voter' slug=suffrage.slug %}" class="btn btn-success">
                    Refaire mon vote</a></div>
                </p>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</div>
<hr>


<div class="row">
    <div class="col textright">
        {% if actions %}
        <button type="button" class="btn btn-light btn-sm" data-toggle="modal" data-target="#historique">
            {% fa5_icon 'bell' title='abonnement' %}Historique
        </button>
        <!-- Modal -->
        <div class="modal fade" id="historique" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
             aria-hidden="true">
            <div class="modal-dialog textcenter" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <div class="row justify-content-center">
                            <div class="col col-sm-12">
                                <h5>Historique</h5>
                            </div>
                        </div>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="contenu historique" id="idHistorique">
                            {%for action in actions %}
                            {% include "notifications/notifications_template3.html" with action=action%}
                            {%endfor%}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% endif %}
    </div>
</div>
<div class="row">
    <div class="col contenusuffrage">
        <h5>Details du suffrage : </h5>
        {{ suffrage.description |safe}}
        <hr>
        {% include 'vote/template_questions.html' %}
        {% if vote %}
        <hr>
        {% if vote.commentaire %}
        <h5>Mon commentaire</h5>
        <div>
            {{vote.commentaire |safe}}
        </div>
        {% else %}
        <h5>(Vous n'avez pas commenté le suffrage)</h5>
        {% endif %}
        {% endif %}

    </div>
</div>

</div>

<hr>

{% include 'commentaires.html' %}

{% endblock %}

vote/templates/vote/sondage_binaire_modifier.html
{% extends 'vote/baseVote.html' %}
{% block title %} - Modifier le sondage{% endblock %}
{% block subtitle %}
<h3>Modifier le sondage : {{sondage_binaire}}</h3>

{% endblock %}
{% block content %}

<div class="row-sm-12 row-lg-6 mx-auto">
    {% include 'form_template.html'%}
</div>

{% endblock %}

vote/templates/vote/suffrage_template.html
{% load activity_tags %}
{% load fontawesome_5 %}
<div class="card article_carte textcenter"  style="background-color:{{suffrage.get_couleur}}">
  <a href="{% url 'vote:lireSuffrage' slug=suffrage.slug %}">
      <div class="article-card-header smallcaps_h ">{{ suffrage.get_type_vote_display }}</div>
  <div class="card-body">
      <h4 class="btn-cat">{{ suffrage.titre }}</h4>
         {{suffrage.get_logo_nomgroupe_html|safe }}
          <span class="badge  {% if suffrage.get_statut.0 == 0%} badge-success  {% elif suffrage.get_statut.0 == 1 %}badge-primary {% else %} badge-light{% endif %}" data-toggle="tooltip" data-placement="bottom" title="{{suffrage.get_statut.1}}">
    {{suffrage.get_statut.1}}
          </span>

        <p class="card-subtitle mb-2 ">
      <p class="text-muted textsmall"> Créé le {{ suffrage.date_creation|date:"DATE_FORMAT" }} {%if suffrage.date_creation != suffrage.date_modification %}(dernière modification le {{ suffrage.date_modification|date:"DATE_FORMAT" }}){%endif%}</p>
  </div>
  </a>
</div>