cal/urls.py
# cal/urls.py

from django.urls import path, include, re_path
from . import views

app_name = 'cal'
urlpatterns = [
    re_path(r'', views.agenda, name='agenda'),
]

fiches/urls.py
# -*- coding: utf-8 -*-
"""bourseLibre URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  re_path(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  re_path(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog__ import urls as blog_urls
    2. Add a URL to urlpatterns:  re_path(r'^blog__/', include(blog_urls))
"""
from django.urls import path, include, re_path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'fiches'

urlpatterns = [
    re_path(r'^accueil-fiches/$', login_required(views.accueil), name="acceuil"),
    re_path(r'^fiches/$', login_required(views.ListeFiches.as_view(), login_url='/auth/login/'), name="index"),
    re_path(r'^ateliers/$', login_required(views.ListeAteliers.as_view(), login_url='/auth/login/'), name="index_ateliers"),
    re_path(r'^fiche/(?P<slug>[-\w]+)$', views.lireFiche, name='lireFiche'),
    re_path(r'^atelier/(?P<slug>[-\w]+)$', views.lireAtelier, name='lireAtelier'),
    re_path(r'^atelier/id/(?P<id>[-\w]+)$', views.lireAtelier_id, name='lireAtelier_id'),
    re_path(r'^modifierFiche/(?P<slug>[-\w]+)$', login_required(views.ModifierFiche.as_view(), login_url='/auth/login/'), name='modifierFiche'),
    re_path(r'^modifierAtelier/(?P<slug>[-\w]+)$', login_required(views.ModifierAtelier.as_view(), login_url='/auth/login/'), name='modifierAtelier'),
    re_path(r'^supprimerFiche/(?P<slug>[-\w]+)$', login_required(views.SupprimerFiche.as_view(), login_url='/auth/login/'), name='supprimerFiche'),
    re_path(r'^ajouterFiche/$', login_required(views.ajouterFiche), name='ajouterFiche'),
    re_path(r'^ajouterAtelier/(?P<fiche_slug>[-\w]+)$', login_required(views.ajouterAtelier), name='ajouterAtelier'),
    re_path(r'^voirFicheTest/$', views.voirFicheTest, name='voirFicheTest'),

]

permagora/urls.py
from django.urls import path, include, re_path
from permagora import views
from django.views.generic import TemplateView
#from fcm_django.api.rest_framework import FCMDeviceAuthorizedViewSet

# On import les vues de Django, avec un nom spécifique
from django.contrib.auth.decorators import login_required

# admin.autodiscover()
from django.contrib import admin

app_name = 'permagora'

urlpatterns = [
    path('gestion/', admin.site.urls),
    re_path(r'^summernote/', include('local_summernote.urls')),
    re_path(r'^captcha/', include('local_captcha.urls')),
    re_path(r'^$', views.bienvenue, name='bienvenue'),
    re_path(r'^planSite/$', views.planSite, name='planSite'),
    re_path(r'^risques/$', views.risques, name='risques'),
    re_path(r'^introduction/$', views.introduction, name='introduction'),
    re_path(r'^preambule/$', views.preambule, name='preambule'),
    re_path(r'^preconisations/$', views.preconisations, name='preconisations'),
    re_path(r'^faq/$', views.faq, name='faq'),
    re_path(r'^contact/$', views.contact, name='contact', ),
    re_path(r'^signer/$', views.signer, name='signer', ),
    re_path(r'^designer/$', views.designer, name='designer', ),
    re_path(r'^statistiques/$', views.statistiques, name='statistiques', ),
    re_path(r'^signataires/$', views.signataires, name='signataires', ),

    re_path(r'^accounts/profil/(?P<user_id>[0-9]+)/$', login_required(views.profil), name='profil', ),
    re_path(r'^accounts/profil/(?P<user_username>[-\w.]+)/$', login_required(views.profil_nom), name='profil_nom', ),
    re_path(r'^accounts/profile/$', login_required(views.profil_courant), name='profil_courant', ),

    re_path(r'^merci/$', views.merci, name='merci'),
    path('auth/', include('django.contrib.auth.urls')),
    re_path(r'^propositions/$', views.propositions, name='propositions', ),
    re_path(r'^organisationPermagora/$', views.organisationPermagora, name='organisationPermagora', ),
    re_path(r'^presentationPermagora/$', views.presentationPermagora, name='presentationPermagora', ),
    re_path(r'^cgu/$', views.cgu, name='cgu', ),
    re_path(r'^liens/$', views.liens, name='liens', ),
    re_path(r'^fairedon/$', views.fairedon, name='fairedon', ),
    re_path(r'^contact_admins/$', views.contact_admins, name='contact_admins',),

    re_path(r'^ajouterPoleCharte/$', views.ajouterPoleCharte, name='ajouterPoleCharte', ),
    re_path(r'^voirProposition/(?P<slug>[-\w]+)$', views.voirProposition, name='voirProposition', ),
    re_path(r'^ajouterVote_plus/(?P<slug>[-\w]+)$', views.ajouterVote_plus, name='ajouterVote_plus', ),
    re_path(r'^ajouterVote_moins/(?P<slug>[-\w]+)$', views.ajouterVote_moins, name='ajouterVote_moins', ),
    path(r'ajouterProposition/', views.ajouterProposition, name='ajouterProposition'),
    path(r'voirNotifications/', views.voirNotifications, name='voirNotifications'),

    re_path(r'^modifierProposition/(?P<slug>[-\w]+)$',
        login_required(views.ModifierProposition.as_view(), login_url='/auth/login/'), name='modifierProposition'),
    ]
urlpatterns += [
    re_path(r'^robots\.txt$', TemplateView.as_view(template_name="permagora/robots.txt", content_type='text/plain')),
]

from django.conf import settings
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'permagora.views.handler404'
handler500 = 'permagora.views.handler500'
handler400 = 'permagora.views.handler400'
handler403 = 'permagora.views.handler403'

photologue/urls.py
from django.urls import path, include, re_path
from django.views.generic import RedirectView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required

from django.contrib.sitemaps.views import sitemap
from .sitemaps import AlbumSitemap, PhotoSitemap

from . import views


"""NOTE: the url names are changing. In the long term, I want to remove the ''
prefix on all urls, and instead rely on an application namespace 'photologue'.

At the same time, I want to change some URL patterns, e.g. for pagination. Changing the urls
twice within a few releases, could be confusing, so instead I am updating URLs bit by bit.

The new style will coexist with the existing '' prefix for a couple of releases.

"""


app_name = 'photologue'

urlpatterns = [
    re_path(r'^album/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/(?P<slug>[\-\d\w]+)/$', login_required(views.AlbumDateDetailView.as_view(month_format='%m')), name='album-detail'),
    re_path(r'^album/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/$', login_required(views.AlbumDayArchiveView.as_view(month_format='%m')), name='album-archive-day'),
    re_path(r'^album/(?P<year>\d{4})/(?P<month>[0-9]{2})/$', login_required(views.AlbumMonthArchiveView.as_view(month_format='%m')), name='album-archive-month'),
    re_path(r'^album/(?P<year>\d{4})/$', login_required(views.AlbumYearArchiveView.as_view()), name='album-archive-year'),
    re_path(r'^album/$', login_required(views.AlbumArchiveIndexView.as_view()), name='album-archive'),
    re_path(r'^$', RedirectView.as_view( url=reverse_lazy('photologue:album-archive'), permanent=True), name='photologue-root'),
    re_path(r'^album/(?P<slug>[\-\d\w]+)/$', login_required(views.AlbumDetailView.as_view()), name='album'),
    re_path(r'^albumlist/$', login_required(views.AlbumListView.as_view()), name='album-list'),
    re_path(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/(?P<slug>[\-\d\w]+)/$', login_required(views.PhotoDateDetailView.as_view(month_format='%m')),
        name='photo-detail'),
    re_path(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/$', login_required(views.PhotoDayArchiveView.as_view(month_format='%m')), name='photo-archive-day'),
    re_path(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/$', login_required(views.PhotoMonthArchiveView.as_view(month_format='%m')), name='photo-archive-month'),
    re_path(r'^photo/(?P<year>\d{4})/$', login_required(views.PhotoYearArchiveView.as_view()), name='photo-archive-year'),
    re_path(r'^photo/$', login_required(views.PhotoArchiveIndexView.as_view()), name='photo-archive'),

    re_path(r'^photo/(?P<slug>[\-\d\w]+)/$', login_required(views.PhotoDetailView.as_view()), name='photo'),
    re_path(r'^photolist/$', login_required(views.PhotoListView.as_view()), name='photo-list'),
    re_path(r'^doclist/$', login_required(views.DocListView.as_view()), name='doc-list'),
    re_path(r'^filtrer_documents/$', views.filtrer_documents, name='filtrer_documents'),
    re_path(r'^ajouterPhoto/(?P<albumSlug>[\-\d\w]+)$', views.ajouterPhoto, name='ajouterPhoto'),
    re_path(r'^ajouterAlbum/$', views.ajouterAlbum, name='ajouterAlbum'),
    path(r'ajouterDocument/<str:article_slug>', views.ajouterDocument, name='ajouterDocument'),
    path(r'associerDocumentArticle/<str:doc_slug>', views.associerDocumentArticle, name='associerDocumentArticle'),

    re_path(r'^modifierAlbum/(?P<slug>[\-\d\w]+)$', login_required(views.ModifierAlbum.as_view(), login_url='/auth/login/'), name='modifierAlbum'),
    re_path(r'^supprimerAlbum/(?P<slug>[\-\d\w]+)$', login_required(views.SupprimerAlbum.as_view(), login_url='/auth/login/'), name='supprimerAlbum'),
    re_path(r'^modifierPhoto/(?P<slug>[\-\d\w]+)$', login_required(views.ModifierPhoto.as_view(), login_url='/auth/login/'), name='modifierPhoto'),
    re_path(r'^supprimerPhoto/(?P<slug>[\-\d\w]+)$', login_required(views.SupprimerPhoto.as_view(), login_url='/auth/login/'), name='supprimerPhoto'),

    re_path(r'^supprimerDocument/(?P<slug>[\-\d\w]+)$',
        login_required(views.SupprimerDocument.as_view(), login_url='/auth/login/'), name='supprimerDocument'),
    re_path(r'^modifierDocument/(?P<slug>[\-\d\w]+)$',
        login_required(views.ModifierDocument.as_view(), login_url='/auth/login/'), name='modifierDocument'),

    re_path(r'^telechargerDocument/(?P<slug>[\-\d\w]+)$',login_required(views.telechargerDocument), name='telechargerDocument'),

    re_path(r'^suivre_albums/$', views.suivre_albums, name='suivre_albums'),
    re_path(r'^suivre_documents/$', views.suivre_documents, name='suivre_documents'),

    re_path(r'^doc-ac/$', views.DocumentAutocomplete.as_view(), name='document-ac', ),
    re_path(r'^doc-ac-asso/$', views.DocumentAutocomplete_asso.as_view(), name='document-ac-asso', ),

]

# sitemaps = {'photologue_galleries': AlbumSitemap,
#             'photologue_photos': PhotoSitemap,
#             }
#
# urlpatterns += [
#     re_path(r'^sitemap.xml$', sitemap, {'sitemaps': sitemaps}),
# ]
#
# from django.contrib.sitemaps import views
#
# urlpatterns += [
#     path(
#         "sitemap.xml",
#         views.index,
#         {"sitemaps": sitemaps},
#         name="django.contrib.sitemaps.views.index",
#     )
#     ]

fiches/models.py
from django.db import models
from bourseLibre.models import Profil, Suivis
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager
from django.utils.translation import gettext_lazy as _
import uuid

class Choix():
    statut_fiche = ('0','En préparation'), ("1","Intégrée dans le kit"), ('2','En attente' ),
    type_fiche = ('0','Bases de la permaculture'), ('1',"Conception du jardin"), ('2','Réalisation du jardin'), ('3','Récolter'),
    couleurs_fiches = {
        '2':'#4DC490', '1':'#C0EDA0', '3':'#00AA8B', '0':'#FCE79C',
        # '0':"#e0f7de", '1':"#dcc0de",
        # '5':"#d1ecdc",'3':"#fcf6bd", '4':"#d0f4de", '7':"#fff2a0",
        # '9':"#ffc4c8", '2':"#bccacf", '10':"#87bfae", '11':"#bcb4b4"
    }
    statut_fiche = ('0', 'proposition'), ('1', "en cours d'écriture"), ("2", "achevée mais pas validée"), ("3", "validée")
    type_difficulte = ('0', 'facile'), ('1', "moyen"), ("2", "difficile")
    type_jauge = ('1', "1"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5")
    type_budget = ('0', "0"), ('1', "1"), ("2", "2"), ("3", "3")
    type_temps = ('1', "1h"), ("2", "2h"), ("3", "3h"), ("4", "4h"), ("5", "6h"), ("6", "1 journée"),  ("7", "plusieurs jours"),  ("8", "plusieurs mois"),
    type_age = ('0', '3-6 ans'), ('1', "7-11 ans"), ("2", "12 ans et plus"), ("3", "3-11ans"), ("4", "Tout public")
    type_atelier = ('0', 'Observation'), ('1', "Experience"), ("2", "Jardinage")

    def get_categorie(num):
        return Choix.type_fiche[int(num)][1]

    def get_difficulte(num):
        return Choix.type_difficulte[int(num)][1]

    def get_age(num):
        return Choix.type_fiche[int(num)][1]

    def get_typeAtelier(num):
        return Choix.type_atelier[int(num)][1]

    def get_couleur_cat(cat):
            return Choix.couleurs_fiches[cat]

class Fiche(models.Model):
    categorie = models.CharField(max_length=30,         
        choices=(Choix.type_fiche),
        default='0', verbose_name=_("categorie"))
    statut = models.CharField(max_length=30,
        choices=(Choix.statut_fiche),
        default='proposition', verbose_name=_("statut de la fiche"))
    numero = models.PositiveIntegerField(blank=False, default=1)
    titre = models.CharField(max_length=120)
    slug = models.SlugField(max_length=100, default=uuid.uuid4)
    contenu = models.TextField(null=True, blank=True)
    objectif = models.TextField(null=True, blank=True)
    en_savoir_plus = models.TextField(null=True, blank=True,)


    date_creation = models.DateTimeField(verbose_name=_("Date de parution"), default=timezone.now)
    date_modification = models.DateTimeField(verbose_name=_("Date de modification"), default=timezone.now)

    date_dernierMessage = models.DateTimeField(verbose_name=_("Date du dernier message"), auto_now=False, blank=True, null=True)
    dernierMessage = models.CharField(max_length=100, default=None, blank=True, null=True)

    tags = TaggableManager(verbose_name=_("Mots-clés"), help_text=_("Une liste de mots clés, séparés par des virgules."), blank=True,)

    class Meta:
        ordering = ('-date_creation', )
        
    def __str__(self):
        return self.titre

    def get_absolute_url(self):
        return reverse('fiches:lireFiche', kwargs={'slug':self.slug})

    def save(self, *args, **kwargs):
        ''' On save, update timestamps '''
        if not self.id:
            self.date_creation = timezone.now()
        return super(Fiche, self).save(*args, **kwargs)

    @property
    def get_couleur(self):
            return Choix.couleurs_fiches[self.categorie]

    @property
    def get_couleur_cat(self,cat):
            return Choix.couleurs_fiches[cat]


class Atelier(models.Model):
    categorie = models.CharField(max_length=30,
                                 choices=(Choix.type_atelier),
                                 default='0', verbose_name=_("categorie"))
    titre = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, default=uuid.uuid4)
    contenu = models.TextField(null=True)
    age = models.CharField(max_length=30,
                                 choices=(Choix.type_age),
                                 default='0', verbose_name=_("age"))
    difficulte = models.CharField(max_length=30,
                                 choices=(Choix.type_difficulte),
                                 default='0', verbose_name=_("difficulté"))
    budget = models.CharField(max_length=30,
                                 choices=(Choix.type_budget),
                                 default='0', verbose_name=_("budget"))
    temps = models.CharField(max_length=30,
                                 choices=(Choix.type_temps),
                                 default='0', verbose_name=_("temps"))
    fiche = models.ForeignKey(Fiche, on_delete=models.CASCADE,)
    date_creation = models.DateTimeField(verbose_name=_("Date de parution"), default=timezone.now)
    date_modification = models.DateTimeField(verbose_name=_("Date de modification"), default=timezone.now)

    class Meta:
        ordering = ('-date_creation',)

    def __str__(self):
        return self.titre

    def get_absolute_url(self):
        return reverse('fiches:lireFiche', kwargs={'slug': self.slug})

    def save(self, commit=False, *args, **kwargs):
        ''' On save, update timestamps '''
        if not self.id:
            self.date_creation = timezone.now()
        return super(Atelier, self).save(*args, **kwargs)

    @property
    def get_couleur(self):
        try:
            return Choix.couleurs_fiches[self.categorie]
        except:
            return Choix.couleurs_fiches["11"]
    #
    # @property
    # def get_difficulte(self):
    #     return Choix.type_difficulte[int(self.difficulte)][1]

    # @property
    # def get_budget_html(self):
    #     return "{% fa5_icon 'euro-sign' %}"
    #     return "{% fa5_icon 'euro-sign' %} ".join([" " for i in range(int(self.budget))])

    @property
    def get_budget_length(self):
        return range(int(self.budget))

    @property
    def get_budget(self):
        return int(self.budget)

    @property
    def get_temps_length(self):
        return range(int(self.temps))

class CommentaireFiche(models.Model):
    auteur_comm = models.ForeignKey(Profil, on_delete=models.CASCADE)
    commentaire = models.TextField()
    fiche = models.ForeignKey(Fiche, on_delete=models.CASCADE)
    date_creation = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.__str__()

    def __str__(self):
        return "(" + str(self.id) + ") "+ str(self.auteur_comm) + ": " + str(self.fiche)

    def get_absolute_url(self):
        return self.commentaire.get_absolute_url()

fiches/templates/fiches/atelier_modifier.html
{% extends 'base_fiches.html' %}
{% block title %} - Modifier l'atelier{% endblock %}
{% block subtitle %}
<h3>Modifier l'atelier</h3>

{% endblock %}
{% block content %}

<div class="row-sm-12 row-lg-6 mx-auto">
    {% include 'form_template.html'%}
</div>


{% endblock %}

{% block comment %}{% endblock %}

fiches/templates/fiches/atelier_template.html
{% load fontawesome_5 %}
{% load fiches_filters %}

<div class="row liste_atelier">
    <div class="col justify-content-center">
    <div class="row">
        <div class="col-sm-12 col-md-8  textcenter">
            <p> <h3><a href="{% url 'fiches:lireAtelier' slug=atelier.slug %}">{{ atelier.titre }}</a>
        </h3></p>
        </div>
        <div class="col-sm-12 col-md-4 textcenter">
            <table class="greenTable">
<thead>
<tr>
<th>Age</th>
<th>Difficulté</th>
<th>Budget</th>
<th>Temps</th>
</tr>
</thead>
<tbody>
<tr>
    <td>{{ atelier.get_age_display }}</td><td>{{ atelier.get_difficulte_display }}</td><td>

      <img  style="max-width: 80%; height: auto;" src="{{STATIC_URL}}img/monnaie{{atelier.get_budget}}.png" alt="cout"/>
    {%for i in atelier.get_budget_length %}
               {% fa5_icon 'coins' %}
               {% comment %}{% fa5_icon 'euro-sign' %} {% endcomment %}
    {%endfor%}

</td>
    <td>
        {{ atelier.get_temps_display }}
         {% comment %}
    {%for i in atelier.get_temps_length %}
               {% fa5_icon 'link' %}
               {% fa5_icon 'clock' %}
    {%endfor%}
         {% endcomment %}
</td>
</tr>
</tbody>
</tr>
</table>

        </div>
    </div>
         {% comment %}
    <div class="row">
        <div class="col-sm-12 ">
            <p>{{ atelier.contenu|safe}}</p>
        </div>
    </div>
         {% endcomment %}
</div>
</div>

fiches/templates/fiches/lireAtelier.html
{% extends 'base_fiches.html' %}
{% load fiches_filters %}
{% load blog_filters %}
{% load fontawesome_5 %}
{% block subtitle %}


{% endblock %}

{% block navbar%}
{%if not request.user.is_authenticated %}
{% else %}
            {% include 'navigationBar.html' %}
{% endif %}
{% endblock%}
{% block content %}

 <div class="row justify-content-center">
    <div class="col-sm-2">

        <div class="btn-group btn-group-justified">
        <a  href="{%if request.user.is_authenticated %}{% url 'fiches:index_ateliers' %}{% endif %}">
        <button class="btn btn-info btn-sm textright" ><i class="fa fa-arrow-left"></i> Ateliers</button>
            </a>
        </div>
    </div>
    <div class="col-sm-8">
        <p class="infos  textepetit textcenter "><a href="{%if request.user.is_authenticated %}{% url 'fiches:lireFiche' slug=atelier.fiche.slug %}{%else%}{% url 'fiches:voirFicheTest' %}{%endif%}"><i class="fa fa-arrow-left"></i> Fiche: {{ atelier.fiche.titre }} </a>
        </p>
    </div>
        <div class="col-sm-2 textright">
            <a href="{%if request.user.is_authenticated %}{% url 'fiches:modifierAtelier' slug=atelier.slug %}{% endif %}">
               <button type="button" class="btn btn-sm btn-warning">
                 &nbsp;Modifier
               </button></a>
        </div>
 </div>



    <div class="row contenu atelier">
    <div class="col justify-content-center">


    <div class="row titre_fiche" style="background-color:{{atelier.fiche.get_couleur}};margin-bottom:15px;">
        <div class="col textcenter" >
              <h2> Atelier : {{ atelier.titre }}</h2>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-sm-12 col-md-4 textcenter">
            <table class="greenTable">
<thead>
<tr>
<th>Age</th>
<th>Difficulté</th>
<th>Budget</th>
<th>Temps</th>
</tr>
</thead>
<tbody>
<tr>
    <td>{{ atelier.get_age_display }}</td><td>{{ atelier.get_difficulte_display }}</td><td>

      <img  style="max-width: 80%; height: auto;" src="{{STATIC_URL}}img/monnaie{{atelier.get_budget}}.png" alt="cout"/>
    {%for i in atelier.get_budget_length %}
               {% fa5_icon 'coins' %}
               {% comment %}{% fa5_icon 'euro-sign' %} {% endcomment %}
    {%endfor%}

</td>
    <td>
        {{ atelier.get_temps_display }}
         {% comment %}
    {%for i in atelier.get_temps_length %}
               {% fa5_icon 'link' %}
               {% fa5_icon 'clock' %}
    {%endfor%}
         {% endcomment %}
</td>
</tr>
</tbody>
</tr>
</table>

        </div>
    </div>
    <div class="row">
        <div class="col-sm-12 ">
            <p>{{ atelier.contenu|safe}}</p>
        </div>
    </div>
</div>
</div>
        </div>



{% endblock %}

fiches/templates/fiches/lireFiche.html
{% extends 'base_fiches.html' %}
{% load fiches_filters %}
{% load blog_filters %}
{% load fontawesome_5 %}
{% block subtitle %}


{% endblock %}
            {% block navbar%}
{%if not request.user.is_authenticated %}
{% else %}
            {% include 'navigationBar.html' %}
{% endif %}
            {% endblock%}
{% block content %}

 <div class="row justify-content-center">

    <div class="col-sm-2">
    </div>
    <div class="col-sm-8">
        <p class="infos  textepetit textcenter "><a href="{%if request.user.is_authenticated %}{% url 'fiches:index'  %}?categorie={{fiche.categorie}}{% endif %}">{{ fiche.get_categorie_display }}</a>, {{ fiche.date_creation|date:"DATE_FORMAT" }}

        </p>
    </div>
        <div class="col-sm-2 textright">
            <a href="{%if request.user.is_authenticated %}{% url 'fiches:modifierFiche' slug=fiche.slug %}{% endif %}">
               <button type="button" class="btn btn-sm btn-warning">
                 &nbsp;Modifier
               </button></a>
        </div>
     </div>
    <div class="row titre_fiche" style="background-color:{{fiche.get_couleur}};">
        <div class="col textcenter" >
              <h2> {{ fiche.numero }}. {{ fiche.titre }}</h2>
        </div>
    </div>
    <div class="row-sm-12 justify-content-center">
        <div class="col-sm-12  fiche_tags">
            <p class="textright"> 
                {% if fiche.tags.names  %}<em>Mots-clés:</em>
           {% for tag in fiche.tags.names %}
            <span class="badge badge-info"> {{tag}}</span>
           {% endfor %}
           {% endif %}  </p>
        </div>
    </div>
  
    <nav class="nav nav-tabs">
      <a class="nav-item nav-link active" href="#p1" data-toggle="tab">Fiche pratique</a>
      <a class="nav-item nav-link" href="#ateliers" data-toggle="tab">Ateliers</a>
      <a class="nav-item nav-link" href="#p3" data-toggle="tab">Discussion</a>
      <a class="nav-item nav-link" href="#p4" data-toggle="tab">En savoir plus...</a>
    </nav>

<div class="tab-content">
  <div class="tab-pane fade show active" id="p1">
    <div class="contenu fiche">
        {% if fiche.objectif%}
        <div class="row">
            <div class="col">
                <p class="fiche_objectif">Objectif : {{ fiche.objectif |safe}}</p>
            </div>
        </div>
        {% endif %}

        <div class="row">
            <div class="col">
               {{ fiche.contenu |safe}}
            </div>
        </div>
    </div>
  </div>

<div class="tab-pane fade" id="ateliers">
    <div class="contenu atelier">
        <div class="col textcenter">
            {%if request.user.is_authenticated %}
            <a href="{% url 'fiches:ajouterAtelier' fiche_slug=fiche.slug%}">
               <button type="button" class="btn btn-sm btn-warning">
                <i class="fa fa-plus"></i> Ajouter un atelier
               </button></a>
            {% endif %}
        </div>
    {% for atelier in ateliers %}
        <div class="row atelier_list" id="atelier{{atelier.slug}}">
        <div class="col">
            {% include 'fiches/atelier_template.html' with atelier=atelier %}
        </div>
        </div>
        {% if not forloop.last %}
    <hr>{% endif %}
    {% endfor %}
    </div>
</div>

<div class="tab-pane fade" id="p3">

    <div class="discussion_fiche">

        {% include 'commentaires.html' %}
  </div>
</div>



    <div class="tab-pane fade" id="p4">
        <div class="contenu ensavoirplus">
            <div class="row">
                <div class="col">
                   {{ fiche.en_savoir_plus |safe}}
                </div>
            </div>
        </div>
    </div>


</div>



{% endblock %}