adherents/urls.py
# -*- coding: utf-8 -*-
"""bourseLibre URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  re_path(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  re_path(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog__ import urls as blog_urls
    2. Add a URL to urlpatterns:  re_path(r'^blog__/', include(blog_urls))
"""
from django.urls import path, include
from . import views, views_phoning
from django.contrib.auth.decorators import login_required

app_name = 'adherents'

urlpatterns = [
    path('<str:asso_slug>/', login_required(views.ListeAdherents.as_view()), name="accueil"),
    path('<str:asso_slug>/accueil_admin/', views.accueil_admin, name="accueil_admin"),
    path('<str:asso_slug>/get_csv_adherents/', views.get_csv_adherents, name="get_csv_adherents"),
    path('<str:asso_slug>/get_infos_adherents_pasajour/', views.get_infos_adherents_pasajour, name="get_infos_adherents_pasajour"),
    path('<str:asso_slug>/get_infos_adherents_ajour/', views.get_infos_adherents_ajour, name="get_infos_adherents_ajour"),
    path('<str:asso_slug>/get_csv_listeMails/', views.get_csv_listeMails, name="get_csv_listeMails"),
    path(r'<str:asso_slug>/infos_adherents/<str:type_info>', views.get_infos_adherent, name="get_infos_adherent"),
    path(r'<str:asso_slug>/infos_listeMail/<int:listeMail_pk>/<str:type_info>', views.get_infos_listeMail, name="get_infos_listeMail"),

    path('<str:asso_slug>/import_csv/', views.import_adherents_ggl, name="import_csv"),
    path('<str:asso_slug>/modif_APE/', views.modif_APE, name="modif_APE"),
    path('<str:asso_slug>/normaliser_adherents/', views.normaliser_adherents, name="normaliser_adherents"),

    path(r'<str:asso_slug>/adherents/', login_required(views.ListeAdherents.as_view()), name="adherent_liste"),
    path(r'<str:asso_slug>/adherent/ajouter/', views.adherent_ajouter, name="adherent_ajouter"),
    path(r'<str:asso_slug>/adherent/ajouterLesMembresGroupe/', views.ajouterLesMembresGroupe, name="ajouterLesMembresGroupe"),
    path(r'<str:asso_slug>/adherent/detail/<int:pk>', login_required(views.AdherentDetailView.as_view()), name="adherent_detail"),
    path(r'<str:asso_slug>/adherent/monProfil', views.monProfil, name="monProfil"),
    path(r'<str:asso_slug>/adherent/modifier/<int:pk>', login_required(views.AdherentUpdateView.as_view()), name="adherent_modifier"),
    path(r'<str:asso_slug>/adherent/adherents_modifier_adresse/<int:pk>', login_required(views.AdherentAdresseUpdateView.as_view()), name="adherents_modifier_adresse"),
    path(r'<str:asso_slug>/adherent/supprimer/<int:pk>', login_required(views.AdherentDeleteView.as_view()), name="adherent_supprimer"),

    path(r'<str:asso_slug>/adhesions/', login_required(views.ListeAdhesions.as_view()), name="adhesion_liste"),
    path(r'<str:asso_slug>/adhesion/creer/<int:adherent_pk>', views.ajouterAdhesion, name="adhesion_creer"),
    path(r'<str:asso_slug>/adhesion/creer/', views.ajouterAdhesion_2, name="adhesion_creer_adherent"),
    path(r'<str:asso_slug>/adhesion/detail/<int:pk>', login_required(views.AdhesionDetailView.as_view()), name="adhesion_detail"),
    path(r'<str:asso_slug>/adhesion/modifier/<int:pk>', login_required(views.AdhesionUpdateView.as_view()), name="adhesion_modifier"),
    path(r'<str:asso_slug>/adhesion/supprimer/<int:pk>', login_required(views.AdhesionDeleteView.as_view()), name="adhesion_supprimer"),

    path(r'<str:asso_slug>/inscriptions/listesInscriptions', login_required(views.ListeInscriptionsMails.as_view()), name="inscriptionMail_liste"),
    path(r'<str:asso_slug>/inscriptions/creer/<int:adherent_pk>', views.creerInscriptionMail_adherent, name="inscriptionMail_adherent"),
    path(r'<str:asso_slug>/inscriptions/creer/', views.creerInscriptionMail, name="inscriptionMail_creer"),
    path(r'<str:asso_slug>/inscriptions/detail/<int:pk>', login_required(views.InscriptionMailDetailView.as_view()), name="inscriptionMail_detail"),
    path(r'<str:asso_slug>/inscriptions/modifier/<int:pk>', login_required(views.InscriptionMailUpdateView.as_view()), name="inscriptionMail_modifier"),
    path(r'<str:asso_slug>/inscriptions/supprimer/<int:pk>', login_required(views.InscriptionMailDeleteView.as_view()), name="inscriptionMail_supprimer"),

    path(r'<str:asso_slug>/comm_adh/modifier/<int:pk>', login_required(views.Comm_adherent_modifier.as_view()), name="comm_adherent_modifier"),
    path(r'<str:asso_slug>/comm_adh/supprimer/<int:pk>', login_required(views.Comm_adherent_supprimer.as_view()), name="comm_adherent_supprimer"),
    path(r'<str:asso_slug>/comm_adh/creer/<int:adherent_pk>', views.ajouter_comm_adh, name="ajouter_comm_adh"),

    path(r'<str:asso_slug>/listesDiffusion/', login_required(views.ListeDiffusion_liste.as_view()), name="listeDiffusion_liste"),
    path(r'<str:asso_slug>/listesDiffusion/creerListe/', views.creerListeDiffusion, name="listeDiffusion_creer"),
    path(r'<str:asso_slug>/listesDiffusion/detail/<int:pk>', login_required(views.ListeDiffusionDetailView.as_view()), name="listeDiffusion_detail"),
    path(r'<str:asso_slug>/listesDiffusion/modifier/<int:pk>', login_required(views.ListeDiffusionUpdateView.as_view()), name="listeDiffusion_modifier"),
    path(r'<str:asso_slug>/listesDiffusion/supprimer/<int:pk>', login_required(views.ListeDiffusionDeleteView.as_view()), name="listeDiffusionsupprimer"),
    path(r'<str:asso_slug>/listesDiffusion/mesListesMails/', views.mesListesMails, name="mesListesMails"),
    path(r'<str:asso_slug>/inscriptions/swap_inscription/<int:listeMail_pk>/<int:adherent_pk>',
         views.swap_inscription, name="swap_inscription"),

    path(r'<str:asso_slug>/listesDiffusion/ajouter/<int:listeDiffusion_pk>/', views.ajouterAdherentAListeDiffusion,
         name="listeDiffusion_ajouterAdherent"),
    path(r'<str:asso_slug>/listesDiffusion/ajouterMail/<int:listeDiffusion_pk>/', views.ajouterMailAListeDiffusion,
         name="listeDiffusion_ajouterMail"),
    path(r'<str:asso_slug>/inscriptions/ajouter/<int:adherent_pk>',
         views.ajouterInscription_AdherentListeDiffusion, name="ajouterInscription_AdherentListeDiffusion"),


    path(r'<str:asso_slug>/phoning/projet/liste', views_phoning.ProjetPhoning_liste.as_view(), name="phoning_projet_liste"),
    path(r'<str:asso_slug>/phoning/projet/simple/<int:projet_pk>', login_required(views_phoning.Contact_liste.as_view()), name="phoning_projet_simple"),
    path(r'<str:asso_slug>/phoning/projet/courant/simple', views_phoning.phoning_projet_courant, name="phoning_projet_courant"),
    path(r'<str:asso_slug>/phoning/projet/courant/complet', login_required(views_phoning.Contact_liste.as_view()), name="phoning_projet_complet"),
    path(r'<str:asso_slug>/phoning/projet/complet/<int:projet_pk>', login_required(views_phoning.Contact_liste.as_view()), name="phoning_projet_complet"),
    #path(r'phoning/contact_ajouter/', views.creerListeDiffusion, name="listeDiffusion_creer"),
    path(r'<str:asso_slug>/phoning/ajouter/acceuil', views_phoning.contact_ajouter_accueil, name="phoning_contact_outils"),
    path(r'<str:asso_slug>/phoning/projet/courant/ajouter', login_required(views_phoning.Contact_ajouter.as_view()), name="phoning_contact_ajouter"),
    path(r'<str:asso_slug>/phoning/projet/courant/ajouter/listetel', views_phoning.phoning_contact_ajouter_listetel, name="phoning_contact_ajouter_listetel"),
    path(r'<str:asso_slug>/phoning/ajouter/csv', views_phoning.phoning_contact_ajouter_csv, name="phoning_contact_ajouter_csv"),
    path(r'<str:asso_slug>/phoning/ajouter/csv_inversernomprenom', views_phoning.phoning_contact_ajouter_csv_inversernomprenom, name="phoning_csv_inversernomprenom"),
    path(r'<str:asso_slug>/phoning/ajouter/csv_editNonVotants', views_phoning.phoning_contact_ajouter_csv_editNonVotants, name="phoning_csv_editNonVotants"),
    path(r'<str:asso_slug>/phoning/ajouter/csv_viti', views_phoning.phoning_contact_ajouter_csv_viti, name="phoning_csv_viti"),
    path(r'<str:asso_slug>/phoning/ajouter/adherents', views_phoning.ajouterAdherents, name="phoning_ajouterAdherents"),
    path(r'<str:asso_slug>/phoning/ajouter/membresGroupe', views_phoning.ajouterMembresGroupe, name="phoning_ajouterMembresGroupe"),
    path(r'<str:asso_slug>/phoning/supprimer/doublons', views_phoning.supprimer_doublons, name="phoning_supprimer_doublons"),
    path(r'<str:asso_slug>/phoning/supprimer/nettoyer_telephones', views_phoning.nettoyer_telephones, name="nettoyer_telephones"),
    path(r'<str:asso_slug>/phoning/supprimer/nettoyer_noms', views_phoning.nettoyer_noms, name="nettoyer_noms"),
    path(r'<str:asso_slug>/phoning/modifier/<int:pk>', login_required(views_phoning.Contact_modifier.as_view()), name="phoning_contact_modifier"),
    path(r'<str:asso_slug>/phoning/supprimer/<int:pk>', login_required(views_phoning.Contact_supprimer.as_view()), name="phoning_contact_supprimer"),
    path(r'<str:asso_slug>/phoning/supprimer2/<int:contact_pk>', views_phoning.contact_supprimer, name="phoning_contact_supprimer2"),
    path(r'<str:asso_slug>/phoning/contact/ajouter/<int:contact_pk>', views_phoning.contactContact_ajouter, name="phoning_contact_contact_ajout"),
    path(r'<str:asso_slug>/phoning/contact/supprimer/<int:contact_contact_pk>', views_phoning.contactContact_supprimer, name="phoning_contact_contact_supprimer"),
    path(r'<str:asso_slug>/phoning/get_csv_contacts/', views_phoning.get_csv_contacts, name="get_csv_contacts"),


    path(r'<str:asso_slug>/phoning/projet/ajouter', login_required(views_phoning.ProjetPhoning_ajouter.as_view()), name="phoning_projet_ajouter"),

cal/urls.py
# cal/urls.py

from django.urls import path, include, re_path
from . import views

app_name = 'cal'
urlpatterns = [
    re_path(r'', views.agenda, name='agenda'),
]

permagora/urls.py
from django.urls import path, include, re_path
from permagora import views
from django.views.generic import TemplateView
#from fcm_django.api.rest_framework import FCMDeviceAuthorizedViewSet

# On import les vues de Django, avec un nom spécifique
from django.contrib.auth.decorators import login_required

# admin.autodiscover()
from django.contrib import admin

app_name = 'permagora'

urlpatterns = [
    path('gestion/', admin.site.urls),
    re_path(r'^summernote/', include('local_summernote.urls')),
    re_path(r'^captcha/', include('local_captcha.urls')),
    re_path(r'^$', views.bienvenue, name='bienvenue'),
    re_path(r'^planSite/$', views.planSite, name='planSite'),
    re_path(r'^risques/$', views.risques, name='risques'),
    re_path(r'^introduction/$', views.introduction, name='introduction'),
    re_path(r'^preambule/$', views.preambule, name='preambule'),
    re_path(r'^preconisations/$', views.preconisations, name='preconisations'),
    re_path(r'^faq/$', views.faq, name='faq'),
    re_path(r'^contact/$', views.contact, name='contact', ),
    re_path(r'^signer/$', views.signer, name='signer', ),
    re_path(r'^designer/$', views.designer, name='designer', ),
    re_path(r'^statistiques/$', views.statistiques, name='statistiques', ),
    re_path(r'^signataires/$', views.signataires, name='signataires', ),

    re_path(r'^accounts/profil/(?P<user_id>[0-9]+)/$', login_required(views.profil), name='profil', ),
    re_path(r'^accounts/profil/(?P<user_username>[-\w.]+)/$', login_required(views.profil_nom), name='profil_nom', ),
    re_path(r'^accounts/profile/$', login_required(views.profil_courant), name='profil_courant', ),

    re_path(r'^merci/$', views.merci, name='merci'),
    path('auth/', include('django.contrib.auth.urls')),
    re_path(r'^propositions/$', views.propositions, name='propositions', ),
    re_path(r'^organisationPermagora/$', views.organisationPermagora, name='organisationPermagora', ),
    re_path(r'^presentationPermagora/$', views.presentationPermagora, name='presentationPermagora', ),
    re_path(r'^cgu/$', views.cgu, name='cgu', ),
    re_path(r'^liens/$', views.liens, name='liens', ),
    re_path(r'^fairedon/$', views.fairedon, name='fairedon', ),
    re_path(r'^contact_admins/$', views.contact_admins, name='contact_admins',),

    re_path(r'^ajouterPoleCharte/$', views.ajouterPoleCharte, name='ajouterPoleCharte', ),
    re_path(r'^voirProposition/(?P<slug>[-\w]+)$', views.voirProposition, name='voirProposition', ),
    re_path(r'^ajouterVote_plus/(?P<slug>[-\w]+)$', views.ajouterVote_plus, name='ajouterVote_plus', ),
    re_path(r'^ajouterVote_moins/(?P<slug>[-\w]+)$', views.ajouterVote_moins, name='ajouterVote_moins', ),
    path(r'ajouterProposition/', views.ajouterProposition, name='ajouterProposition'),
    path(r'voirNotifications/', views.voirNotifications, name='voirNotifications'),

    re_path(r'^modifierProposition/(?P<slug>[-\w]+)$',
        login_required(views.ModifierProposition.as_view(), login_url='/auth/login/'), name='modifierProposition'),
    ]
urlpatterns += [
    re_path(r'^robots\.txt$', TemplateView.as_view(template_name="permagora/robots.txt", content_type='text/plain')),
]

from django.conf import settings
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'permagora.views.handler404'
handler500 = 'permagora.views.handler500'
handler400 = 'permagora.views.handler400'
handler403 = 'permagora.views.handler403'

adherents/templates/adherents/accueil_admin.html
{% extends 'base_adherents.html' %}
{% block subtitle %}

<div class="row">
    <div class="col textcenter">
       <h3> Adherents</h3>
    </div>
</div>

{% endblock %}
{% block content %}

<div class="row justify-content-center">
    <div class="col-sm-12 textcenter">
        <div class="btn-group btn-group-justified">
         <a href="{% url 'adherents:accueil' asso_slug=request.session.asso_slug %}">
        <button type="button" class="btn btn-success" >
               Liste des adherents
            </button>
         </a>
         <a href="{% url 'adherents:adhesion_liste' asso_slug=request.session.asso_slug %}">
            <button type="button" class="btn btn-success" >
               liste adhesions
            </button>
         </a>
        {% if request.user.is_superuser %}
             <a href="{% url 'adherents:import_csv' asso_slug=request.session.asso_slug %}">
                <button type="button" class="btn btn-success" >
                   import DB adherents
                </button>
             </a>
             <a href="{% url 'adherents:modif_APE'  asso_slug=request.session.asso_slug %}">
                <button type="button" class="btn btn-success" >
                   Modif APE
                </button>
             </a>
             <a href="{% url 'adherents:admin_restaurerAdherents' asso_slug=request.session.asso_slug %}">
                <button type="button" class="btn btn-success" >
                   admin_restaurerAdherents
                </button>
             </a>
        {% endif %}
    </div>
   </div>

   </div>
<div class="row justify-content-center">
    <div class="col-sm-12 textcenter">
        {{msg|safe}}
   </div>

   </div>

{% endblock %}

adherents/templates/adherents/adherent_detail.html
{% extends 'base_adherents.html' %}

{% block header%}
{% load leaflet_tags %}
{% load static %}
{% load fontawesome_5 %}
{% leaflet_js %}
{% leaflet_css %}
{% endblock %}

{% block subtitle %}

<div class="row rowcentre" id="titre">
    <div class="col-sm-12 textcenter">
        {%if request.user.is_superuser or is_membre_bureau %}
        <div class="btn-group">
            <a href="{%if request.user.is_authenticated %}{% url 'adherents:adherent_modifier' pk=adherent.pk  asso_slug=request.session.asso_slug %}{% endif %}">
                <button type="button" class="btn btn-sm btn-warning">
                    &nbsp;Modifier
                </button>
            </a>
        </div>
        {% endif %}
        {%if request.user.is_superuser or is_membre_bureau %}
        <a href="{%if request.user.is_authenticated %}{% url 'adherents:adherent_supprimer' pk=adherent.pk asso_slug=request.session.asso_slug %}{% endif %}">
            <button type="button" class="btn btn-sm btn-danger">
                &nbsp;Supprimer
            </button>
        </a>
        {% endif %}
    </div>
</div>
<div class="row titre_adherents">
    <div class="col textcenter">
        <h3> {{adherent}} </h3>
    </div>
</div>

{% endblock %}
{% block content %}
{% if request.user == adherent.profil %}
<div class="row justify-content-center">
    <div class="col-sm-12 col-md-10 textcenter">
        <a class="btn btn-success" href="{% url 'adherents:mesListesMails' asso_slug=request.session.asso_slug %}">Voir mes abonnements aux listes de diffusion</a>
    </div>
</div>
{% endif %}
<div class="row justify-content-center">
    <div class="col-sm-12 col-md-10">
        <table class="table table-condensed tablepanier table-striped table-middle {% if request.user.css_dark %}table-dark{% endif %}">
            <tbody>
            {% if adherent.profil %}
            <tr>
                <td style="width:250px">Profil :</td>
                <td><a href="{{adherent.profil.get_absolute_url}}">{{adherent.profil}}</a></td>
            </tr>
            {% endif %}
            <tr>
                <td style="width:250px">Nom :</td>
                <td>{{adherent.nom}}</td>
            </tr>
            <tr>
                <td style="width:250px">Prénom :</td>
                <td>{{adherent.prenom}}</td>
            </tr>
            <tr>
                <td style="width:250px">Email :</td>
                <td>{{adherent.email}}</td>
            </tr>
            {% if adherent.adresse.telephone %}
            <tr>
                <td style="width:250px">Telephone *:</td>
                <td>{{ adherent.adresse.telephone }}</td>
            </tr>
            {% endif %}
            </tbody>
        </table>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        {%if request.user.is_superuser or is_membre_bureau  %}
        <a href="{% url 'adherents:adherents_modifier_adresse' pk=adherent.adresse.pk asso_slug=request.session.asso_slug %}">
            <button type="button" class="btn btn-sm btn-warning">
                <span class="glyphicon glyphicon-plus"></span>&nbsp;Modifier
            </button>
        </a>
        {%endif%}
        {%if request.user.is_superuser %}
        <a href="https://www.perma.cat/gestion/bourseLibre/adresse/{{adherent.adresse.id}}/change/">
            <button type="button" class="btn btn-sm btn-warning">
                <span class="glyphicon glyphicon-plus"></span>&nbsp;Admin Modifier
            </button>
        </a>
        {%endif%}
        <table class="table table-condensed tablepanier table-striped table-middle {% if request.user.css_dark %}table-dark{% endif %}">
            <tbody>
            {%if adherent.adresse.rue %}
            <tr>
                <td style="width:250px">Adresse ^:</td>
                <td>{{ adherent.adresse.rue }}</td>
            </tr>
            {% endif %}
            {%if adherent.adresse.commune %}
            <tr>
                <td style="width:250px">Commune :</td>
                <td>{{ adherent.adresse.commune }}</td>
            </tr>
            {% endif %}
            {%if adherent.adresse.code_postal %}
            <tr>
                <td style="width:250px">Code postal :</td>
                <td>{{ adherent.adresse.code_postal }}</td>
            </tr>
            {% endif %}
            <tr>
                <td style="width:200px">lat/lon ^:</td>
                <td>{{ adherent.adresse.latitude }} / {{ adherent.adresse.longitude }}</td>
            </tr>

            </tbody>
        </table>
    </div>

    <div class="col-md-6">
        <style>leaflet-container {width:  100%;height: 90vh;}</style>
        <script type="text/javascript">
                function map_init_basic (map, options) {
                var greenIcon = L.icon({
                      iconUrl: '{% static 'img/marker-icon-2x-green.png' %}',
                      shadowUrl: '{% static 'img/marker-shadow.png' %}',
                      iconSize: [25, 41],
                      iconAnchor: [12, 41],
                      popupAnchor: [1, -34],
                      shadowSize: [41, 41]
                });
                var lat = {{adherent.adresse.get_latitude}};
                var lon = {{adherent.adresse.get_longitude}};
                L.marker([lat, lon], {icon: greenIcon}).addTo(map);
                map.panTo(new L.LatLng(lat, lon));
            }


        </script>
        {% leaflet_map "yourmap" callback="window.map_init_basic" %}
    </div>
</div>

{% if is_membre_bureau or request.user == adherent.profil  %}
<hr>
<h5>Cotisations :</h5>
{% include 'adherents/template_adhesion_liste2.html' %}

{% if is_membre_bureau %}
<div class="row">
    <div class="col-md-12 textcenter">
        <a href="{% url 'adherents:adhesion_creer' adherent_pk=adherent.pk asso_slug=adherent.asso.slug %}">
            <button type="button" class="btn btn-sm btn-danger">
                <span class="fa fa-plus"></span>&nbsp;Ajouter une cotisation
            </button>
        </a>
    </div>
</div>
<hr>
{% endif %}
<h5>Listes de diffusion :</h5>
{% include 'adherents/template_inscriptionmail_liste.html' %}

{% if is_membre_bureau %}
<div class="row">
    <div class="col-md-12 textcenter">
        <a href="{% url 'adherents:inscriptionMail_adherent' adherent_pk=adherent.pk asso_slug=request.session.asso_slug %}">
            <button type="button" class="btn btn-sm btn-danger">
                <span class="fa fa-plus"></span>&nbsp;Ajouter l'adhérent à une liste
            </button>
        </a>
    </div>
</div>

<hr>
<h5>Commentaires :</h5>
{% include 'adherents/template_comm_adh_liste.html' %}

<div class="row">
    <div class="col-md-12 textcenter">
<a href="{% url 'adherents:ajouter_comm_adh' adherent_pk=adherent.pk asso_slug=request.session.asso_slug%}">
    <button type="button" class="btn btn-sm btn-danger">
        <span class="fa fa-plus"></span>&nbsp;Ajouter un commentaire
    </button>
</a>
    </div>
</div>
{% endif %}


{% endif %}

{% endblock %}

adherents/templates/adherents/adherent_modifier.html
{% extends 'base_adherents.html' %}
{% block subtitle %}

<div class="row">
    <div class="col textcenter">
       <h3> Modifier l'adhérent {{adherent}} </h3>
    </div>
</div>

<div class="row-sm-12 row-lg-6 mx-auto textcenter justify-content-center">
<a href="{% url 'adherents:adherents_modifier_adresse' pk=adherent.adresse.pk asso_slug=request.session.asso_slug %}">
    <button type="button" class="btn btn-sm btn-warning">
        <span class="glyphicon glyphicon-plus"></span>&nbsp;Modifier l'adresse / telephone
    </button>
</a>
</div>

{% endblock %}

{% block content %}

<div class="row-sm-12 row-lg-6 mx-auto">
    <form id="myForm" class="form-horizontal" role="form" action="" method="post"
        enctype="multipart/form-data">
            {% include 'form_template.html'%}
    </form>
</div>


{% endblock %}

adherents/templates/adherents/adhesion_ajouter.html
{% extends 'base_adherents.html' %}

{% block content %}
<div class="row">
    <div class="col textcenter">
       <h3> Ajouter une cotisation {% if adherent %}à {{adherent}} {% endif %}</h3>
    </div>
</div>

<div class="row-sm-12 row-lg-6 mx-auto">
    <form id="myForm" class="form-horizontal" role="form" action="" method="post"
        enctype="multipart/form-data">
            {% include 'form_template.html'%}
    </form>
</div>
{% endblock %}

adherents/templates/adherents/adresse_modifier.html
{% extends 'base_adherents.html' %}
{% block subtitle %}

<div class="row">
    <div class="col textcenter">
       <h3> Modifier l'adresse  </h3>
    </div>
</div>

{% endblock %}
{% block content %}

<div class="row-sm-12 row-lg-6 mx-auto">
    <form id="myForm" class="form-horizontal" role="form" action="" method="post"
        enctype="multipart/form-data">
            {% include 'form_template.html'%}
    </form>
</div>
{% endblock %}

adherents/templates/adherents/listediffusionconf_list.html
{% extends 'base_adherents.html' %}

{% block header%}
{% load leaflet_tags %}
{% load static %}
{% load fontawesome_5 %}
{% leaflet_js %}
{% leaflet_css %}
{% endblock %}

{% block subtitle %}
<div class="row titre_adherents">
    <div class="col textcenter">
        <h3>Les Listes de diffusion par Mail </h3>

        <a class="btn btn-primary"   href="{% url 'adherents:mesListesMails' %}">Voir mes abonnements</a>
    </div>
</div>
{% if request.user.estmembre_bureau_conf %}
<div class="row ">
    <div class="col textcenter">
        <a class="btn btn-danger"   href="{% url 'adherents:listeDiffusionConf_creer' %}">Ajouter une liste</a>
    </div>
</div>
{% endif %}
{% endblock %}


{% block content %}

 {% include 'adherents/template_listeDiffusionConf_liste.html'%}

{% if request.user.estmembre_bureau_conf %}
        <h4 class="textcenter" >Pour le bureau :</h4>
<hr>
<div class="row ">
    <div class="col textcenter">

    <a href="{% url 'adherents:get_csv_listeMails' %}" target="_blank" rel="noopener noreferrer nofollow">
        <button type="button" class="btn btn-sm btn-primary">
            &nbsp;Exporter en CSV pour Google
        </button>
    </a>
		<a class="btn btn-success" href="{% url 'adherents:inscriptionMail_liste' %}">Gérer la liste des inscriptions</a></li>
    </div>
</div>


<div class="row">
    <div class="col textcenter">
        <table class="table table-condensed tableprofils table-striped ²">
            <thead><tr>
                <th>Nom de la liste</th>
                <th>Adhérents</th>
                <th></th>
            </tr></thead>
            <tbody>
{% for nom, adherents in dico_ListesBase.items %}
            <tr>
                <td> {{nom}}({{adherents|length}})</td>
                <td>
                    {%for m in adherents %}
                        {{m}} {% if not forloop.last %}, {% endif%}
                    {%endfor%}
                </td>
                <td>
                    <a onclick="copyToClipboard('{%for m in adherents %} {{m}}{% if not forloop.last %}, {% endif%}{%endfor%}')">
                        <button type="button" class="btn btn-sm btn-primary">
                            Copier la liste des mails
                        </button>
                    </a>
                </td>
            </tr>
{% endfor %}
            </tbody>
        </table>

    </div>
</div>
<hr>
 <div class="textcenter">
        <button id="btn-archives"  type="button" class="btn btn-lg" onclick="toggle_visibility('historique');" data-toggle="tooltip" data-placement="bottom" title="Cliquez pour afficher les archives">
            Afficher l'historique
        </button>
    </div>
    <div id="historique" style='display:none;'>
 {% include 'adherents/template_actions.html'%}
    </div>

{% endif %}
{% endblock %}