cal/urls.py
# cal/urls.py

from django.urls import path, include, re_path
from . import views

app_name = 'cal'
urlpatterns = [
    re_path(r'', views.agenda, name='agenda'),
]

jardins/urls.py
# -*- coding: utf-8 -*-
"""bourseLibre URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  re_path(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  re_path(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog__ import urls as blog_urls
    2. Add a URL to urlpatterns:  re_path(r'^blog__/', include(blog_urls))
"""
from django.urls import path, include, re_path
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'jardins'

urlpatterns = [
    re_path(r'^$', views.accueil, name="accueil"),

    ## plantes
    re_path(r'^accueil_admin/$', views.accueil_admin, name="accueil_admin"),
    re_path(r'^import_db_inpn_0/$', views.import_db_inpn_0, name="import_db_inpn_0"),
    re_path(r'^import_db_inpn_1/$', views.import_db_inpn_1, name="import_db_inpn_1"),
    re_path(r'^import_db_inpn_2/$', views.import_db_inpn_2, name="import_db_inpn_2"),
    re_path(r'^import_db_inpn_3/$', views.import_db_inpn_3, name="import_db_inpn_3"),
    re_path(r'^import_db_inpn_4/$', views.import_db_inpn_4, name="import_db_inpn_4"),
    re_path(r'^import_grainotheque_rtg_1/$', views.import_grainotheque_rtg_1, name="import_grainotheque_rtg_1"),
    re_path(r'^import_grainotheque_rtg_2/$', views.import_grainotheque_rtg_2, name="import_grainotheque_rtg_2"),
    path(r'plantes/', views.ListePlantes.as_view(), name="plantes"),
    path(r'voir_plante/<str:cd_nom>', views.voir_plante, name="voir_plante"),
    path(r'voir_plante_nom/', views.voir_plante_nom, name="voir_plante_nom"),
    path(r'voir_plante_recherche/', views.voir_plante_recherche, name="voir_plante_recherche"),
    re_path(r'^plante-ac/$', views.PlanteAutocomplete.as_view(), name='plante-ac',),
    re_path(r'^ajouterPlante/$', views.ajouter_plante, name="ajouter_plante"),
    re_path(r'^chercher_plante/$', views.chercher_plante, name="chercher_plante"),

    ##jardins
    path(r'jardins/carte/', views.carte_jardins, name="carte_jardins"),
    path(r'jardiniers/carte/', views.carte_jardiniers, name="carte_jardiniers"),
    path(r'grainotheques/carte/', views.carte_graino, name="carte_graino"),

    path(r'jardin/ajouterJardin_intro/', views.ajouterJardin_intro, name="ajouterJardin_intro"),
    path(r'jardin/ajouter/', views.AjouterJardin.as_view(), name="jardin_ajouter"),
    path(r'jardin/jardin_ajouterAdresse/<str:slug>', views.jardin_ajouterAdresse, name="jardin_ajouterAdresse"),
    path(r'jardin/jardin_ajouterSalon/<str:slug>', views.jardin_ajouterSalon, name="jardin_ajouterSalon"),
    path(r'jardin/modifierAdresse/<str:slug>', views.jardin_modifierAdresse, name="jardin_modifierAdresse"),
    path(r'jardin/modifier/<str:slug>', login_required(views.ModifierJardin.as_view()), name="jardin_modifier"),
    path(r'jardin/jardin_supprimer/<str:slug>', login_required(views.SupprimerJardin.as_view()), name="jardin_supprimer"),
    path(r'jardin/voir/<str:slug>', views.JardinDetailView.as_view(), name="jardin_lire"),
    path(r'jardin/voirMonJardin/', views.voir_monJardin, name="voir_monJardin"),
    path(r'jardin/voir_autreJardin/', views.voir_autreJardin, name="voir_autreJardin"),
    path(r'jardin/ajouterPlante/<str:slug>', views.jardin_ajouterPlante, name="jardin_ajouterPlante"),
    path(r'jardin/ajouterPlante_monJardin/<int:plante_pk>', views.ajouterPlante_monJardin, name="ajouterPlante_monJardin"),
    path(r'jardin/ajouterPlante/<int:jardin_pk>/<int:plante_pk>', views.jardin_ajouterPlante_pk, name="jardin_ajouterPlante_pk"),
    path(r'jardin/modifierPlante/<str:slug_jardin>/<int:pk>', views.jardin_modifierPlante, name="jardin_modifierPlante"),
    #path(r'jardin/supprimerPlante/<str:slug_jardin>/<int:pk>', views.jardin_supprimerPlante, name="jardin_supprimerPlante"),
    path(r'jardin/supprimerPlante/<str:slug_jardin>/<int:pk>', login_required(views.PlanteDJDeleteView.as_view()), name="jardin_supprimerPlante"),
    path(r'jardin/supprimerPlantes/<str:slug_jardin>', views.jardin_supprimerPlantes, name="jardin_supprimerPlantes"),
    path(r'jardin/editInfosPlante/<int:pk>', login_required(views.ModifierInfoPlante.as_view()), name="jardin_editInfosPlante"),

    path(r'jardin/inscription/<str:slug>', views.inscriptionJardin, name='inscriptionJardin'),
    path(r'jardin/annulerInscription/<str:slug>', views.annulerInscription, name='annulerInscription'),
    path(r'jardin/contacterInscritsJardin/<str:slug>', views.contacterInscritsJardin, name='contacterInscritsJardin'),

    path(r'grainotheque/ajouter/', login_required(views.AjouterGrainotheque.as_view()), name="grainotheque_ajouter"),
    path(r'grainotheque/modifier/<str:slug>', login_required(views.ModifierGrainotheque.as_view()), name="grainotheque_modifier"),
    path(r'grainotheque/editInfosGraine/<int:pk>', login_required(views.ModifierInfoGraine.as_view()), name="grainotheque_editInfosGraine"),
    path(r'jardin/supprimer_grainotheque/<str:slug>', login_required(views.SupprimerGrainotheque.as_view()), name="grainotheque_supprimer"),
    path(r'grainotheque/voir/<str:slug>', views.GrainothequeDetailView.as_view(), name="grainotheque_lire"),
    path(r'grainotheque/voirMaGraino/', views.voir_maGrainotheque, name="voir_maGrainotheque"),
    path(r'grainotheque/ajouterGraine/<str:slug>', views.graino_ajouterGraine, name="graino_ajouterGraine"),
    path(r'grainotheque/ajouterGraine_pk/<int:graino_pk>/<int:plante_pk>', views.graino_ajouterGraine_pk, name="graino_ajouterGraine_pk"),
    path(r'grainotheque/ajouterPlante_maGrainotheque/<int:plante_pk>', views.ajouterPlante_maGrainotheque, name="ajouterPlante_maGrainotheque"),
    path(r'grainotheque/modifierGraine/<str:slug_graino>/<int:pk>', views.graino_modifierGraine, name="graino_modifierGraine"),
    path(r'grainotheque/ajouterAdresse/<str:slug>', views.grainotheque_ajouterAdresse, name="grainotheque_ajouterAdresse"),
    path(r'grainotheque/modifierAdresse/<str:slug>', views.grainotheque_modifierAdresse, name="grainotheque_modifierAdresse"),
    path(r'grainotheque/supprimerGraines/<str:slug>', views.grainotheque_supprimerGraines, name="grainotheque_supprimerGraines"),
    ]

permagora/urls.py
from django.urls import path, include, re_path
from permagora import views
from django.views.generic import TemplateView
#from fcm_django.api.rest_framework import FCMDeviceAuthorizedViewSet

# On import les vues de Django, avec un nom spécifique
from django.contrib.auth.decorators import login_required

# admin.autodiscover()
from django.contrib import admin

app_name = 'permagora'

urlpatterns = [
    path('gestion/', admin.site.urls),
    re_path(r'^summernote/', include('local_summernote.urls')),
    re_path(r'^captcha/', include('local_captcha.urls')),
    re_path(r'^$', views.bienvenue, name='bienvenue'),
    re_path(r'^planSite/$', views.planSite, name='planSite'),
    re_path(r'^risques/$', views.risques, name='risques'),
    re_path(r'^introduction/$', views.introduction, name='introduction'),
    re_path(r'^preambule/$', views.preambule, name='preambule'),
    re_path(r'^preconisations/$', views.preconisations, name='preconisations'),
    re_path(r'^faq/$', views.faq, name='faq'),
    re_path(r'^contact/$', views.contact, name='contact', ),
    re_path(r'^signer/$', views.signer, name='signer', ),
    re_path(r'^designer/$', views.designer, name='designer', ),
    re_path(r'^statistiques/$', views.statistiques, name='statistiques', ),
    re_path(r'^signataires/$', views.signataires, name='signataires', ),

    re_path(r'^accounts/profil/(?P<user_id>[0-9]+)/$', login_required(views.profil), name='profil', ),
    re_path(r'^accounts/profil/(?P<user_username>[-\w.]+)/$', login_required(views.profil_nom), name='profil_nom', ),
    re_path(r'^accounts/profile/$', login_required(views.profil_courant), name='profil_courant', ),

    re_path(r'^merci/$', views.merci, name='merci'),
    path('auth/', include('django.contrib.auth.urls')),
    re_path(r'^propositions/$', views.propositions, name='propositions', ),
    re_path(r'^organisationPermagora/$', views.organisationPermagora, name='organisationPermagora', ),
    re_path(r'^presentationPermagora/$', views.presentationPermagora, name='presentationPermagora', ),
    re_path(r'^cgu/$', views.cgu, name='cgu', ),
    re_path(r'^liens/$', views.liens, name='liens', ),
    re_path(r'^fairedon/$', views.fairedon, name='fairedon', ),
    re_path(r'^contact_admins/$', views.contact_admins, name='contact_admins',),

    re_path(r'^ajouterPoleCharte/$', views.ajouterPoleCharte, name='ajouterPoleCharte', ),
    re_path(r'^voirProposition/(?P<slug>[-\w]+)$', views.voirProposition, name='voirProposition', ),
    re_path(r'^ajouterVote_plus/(?P<slug>[-\w]+)$', views.ajouterVote_plus, name='ajouterVote_plus', ),
    re_path(r'^ajouterVote_moins/(?P<slug>[-\w]+)$', views.ajouterVote_moins, name='ajouterVote_moins', ),
    path(r'ajouterProposition/', views.ajouterProposition, name='ajouterProposition'),
    path(r'voirNotifications/', views.voirNotifications, name='voirNotifications'),

    re_path(r'^modifierProposition/(?P<slug>[-\w]+)$',
        login_required(views.ModifierProposition.as_view(), login_url='/auth/login/'), name='modifierProposition'),
    ]
urlpatterns += [
    re_path(r'^robots\.txt$', TemplateView.as_view(template_name="permagora/robots.txt", content_type='text/plain')),
]

from django.conf import settings
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'permagora.views.handler404'
handler500 = 'permagora.views.handler500'
handler400 = 'permagora.views.handler400'
handler403 = 'permagora.views.handler403'

jardins/templates/base_plantes.html
{% extends 'base_jardin.html' %}
{% load static %}
{% block header %}
<link rel="stylesheet" href="{% static 'jardins/garelick/css/style_jardins.css' %}">
{% endblock %}
 {% block panel-heading %}{%endblock%}
{% block div-container-global %} style="padding-top:0;"{% endblock%}
{% block surtitle %}
Jardinothèque Catalane
{% endblock %}


{% block titreBlog %}
<h1>Jardinothèque de Perma.Cat</h1>
{% endblock  %}

{%block loader %}
{% endblock  %}
{%block bodyEntete%} style="visibility: collapse;" {%endblock%}
{% block navbar %}
{% endblock %}
{% block submenu %}
<div class="sticky-top">
    <nav class="navbar {%if request.user.css_dark %} navbar-dark bg-primary {% else %}  navbar-light bs-dark {% endif %} navbar-expand-xl  shadow-petit">
        <button class="navbar-toggler navbar-toggler-right navbar-btn" type="button" data-toggle="collapse" data-target="#navbar2" aria-controls="navbar2" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
         </button>
        <div class="navbar-collapse collapse mx-auto" id="navbar2">
    <ul class="navbar-nav mx-auto subnavbar align-items-center">
		<li class="nav-item">
                <a href="{% url 'jardins:accueil' %}">
            <div class="row row_banniere_ordi" >
                <img  src="{% static 'jardins/garelick/images/jardinotheque_logo.png' %}"  height="50px" style="height:50px;" alt="Logo_jardins"/>
            </div>
            </a>
        </li>
		<li class="nav-item nav-jardin"><a class="dropdown-item"   href="{% url 'jardins:carte_jardins' %}"> La Carte</a></li>
		<li class="nav-item nav-jardin"><a class="dropdown-item"   href="{% url 'jardins:plantes' %}"> Les Plantes</a></li>
        {% if request.user.adherent_jp %}
            <li class="nav-item nav-jardin"><a class="dropdown-item"   href="{% url 'jardins:carte_jardiniers' %}"> Les Jardinier-es </a></li>
            <li class="nav-item nav-jardin"><a class="dropdown-item"   href="{% url 'blog:index_asso' asso='jp'%}#ref-titre"> Forum </a></li>
            <li class="nav-item nav-jardin"><a class="dropdown-item"   href="{% url 'marche' %}?asso=jp#ref-titre"> Annonces </a></li>
        {% endif %}
		<li class="nav-item "><a href="{% url 'bienvenue' %}"><img  src="{% static 'favicon.ico' %}"  height="44" alt="Retour sur perma.cat"/></a>
        </li>
                {% comment %}
        <li class="nav-item dropdown">
           <a data-toggle="dropdown" class="nav-link dropdown-toggle  navbar-menu" href="{% url 'profil_courant' %}" aria-haspopup="true" aria-expanded="false"  >
             <i class="fa fa-plus iconleft" title="Ajouter"></i>
           </a>
            <ul class="dropdown-menu dropdown-menu-right nav9-dropdown" aria-labelledby="navbarDropdownMenuLink">
                <li class="nav-item nav-jardin"><a class="dropdown-item"   href="{% url 'jardins:ajouterJardin_intro'  %}"> Ajouter un jardin </a></li>
                <li class="nav-item nav-jardin"><a class="dropdown-item"   href="{% url 'jardins:grainotheque_ajouter'  %}"> Ajouter une grainothèque </a></li>
            </ul>
        </li>
                {% endcomment %}
            </ul>
        </div>
    </nav>

</div>
{% endblock %}

jardins/templates/template_annuaire_graino.html
{% load app_filters %}
{% load avatar_tags %}

{% block header %}
{% load static %}
{% endblock %}

{% block content %}

{% if grainotheques %}
   <div class="row">
    <div class="col-md-12">
        <div style="overflow-x:auto;">
    <table class="table table-condensed tablejardin table-striped table-middle {% if request.user.css_dark %}table-dark{% endif %} sortable">
        <thead class="thead-inverse">
            <tr>
                <th style="min-width:40%;">Nom</th>
                <th>Type</th>
                {% if request.user.is_authenticated %}<th>Email</th>{% endif %}
                <th>Commune</th>
            </tr>
        </thead>
        <tbody>
        {% for grainotheque in grainotheques %}
        <tr>
           <td style="width-min:50%;" class="titre_forum"><a href="{% url 'jardins:grainotheque_lire' grainotheque.slug %}">{{ grainotheque.titre }}</a></td>
            <td><a href="{% url 'jardins:grainotheque_lire' grainotheque.slug  %}">{{ grainotheque.get_categorie_display }}</a></td>
           {% if request.user.is_authenticated %}<td><a href="{% url 'jardins:grainotheque_lire' grainotheque.slug  %}">{{ grainotheque.email_contact }}</a></td>{% endif %}
            {% if not request.user.is_authenticated %}
                {% if grainotheque.visibilite_annuaire == '0' %}
                <td>{%if grainotheque.adresse.commune %}{{ grainotheque.adresse.commune }} ({{ grainotheque|distance:request.user }} km){% else %}-{% endif %}</td>
                 {% else %}
                <td> - </td>
                {% endif %}
            {% else %}
                {% if grainotheque.visibilite_annuaire == '0' or grainotheque.visibilite_annuaire == '1' %}
                <td>{%if grainotheque.adresse.commune %}{{ grainotheque.adresse.commune }} ({{ grainotheque|distance:request.user}} km) {% else %}-{% endif %}</td>
                {% else %}
                <td> - </td>
                {% endif %}
            {% endif %}
            <td></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
    </div>
    </div>


{% endif %}
{% endblock %}

jardins/templates/template_annuaire_jardin.html
{% load app_filters %}
{% load avatar_tags %}

{% block header %}
{% load static %}
{% endblock %}

{% block content %}

   <div class="row">
    <div class="col-md-12">
        <div style="overflow-x:auto;">
    <table class="table table-condensed tablejardin table-striped table-middle {% if request.user.css_dark %}table-dark{% endif %} sortable">
        <thead class="thead-inverse">
            <tr>
                <th style="min-width:40%;">Nom</th>
                <th>Type de jardin</th>
                {% if request.user.is_authenticated %}<th>Email</th>{% endif %}
                <th>Commune</th>
            </tr>
        </thead>
        <tbody>
        {% for jardin in jardins %}
        <tr>
           <td style="width-min:30%;" class="titre_forum"><a href="{% url 'jardins:jardin_lire' jardin.slug %}">{{ jardin.titre }}</a></td>
            <td>{{ jardin.get_categorie_display }}</td>
            {% if request.user.is_authenticated %}<td>{{ jardin.email_contact }}</td>{% endif %}
            <td>{%if jardin.adresse.commune %}{{ jardin.adresse.commune }} ({{ jardin|distance:request.user }} km) {% else %}-{% endif %}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
    </div>
    </div>


{% endblock %}